[package]
name = "lints"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "format_error"
path = "ui/format_error.rs"

# See `README.md` before bumping the version.
# Remember to update the version in `ci/Dockerfile` as well.
[dependencies]
clippy_utils = { git = "https://github.com/risingwavelabs/clippy", rev = "61e1d2fd7062e46ccf1237707ee6da5aac018f70" }
dylint_linting = "3.1.0"
itertools = "0.12"

[dev-dependencies]
dylint_testing = "3.1.0"

# UI test dependencies
anyhow = "1"
thiserror-ext = "0.1"
tracing = "0.1"

[package.metadata.rust-analyzer]
rustc_private = true
