init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.range_partition_upsert_table',
    '''
    CREATE TABLE demo_db.range_partition_upsert_table (
    id int,
    v1 int,
    v2 long,
    v3 string,
    v4 date
    ) USING iceberg
    PARTITIONED BY (days(v4))
    TBLPROPERTIES ('format-version'='2');
    '''
]

slt = 'test_case/iceberg_sink_range_partition_upsert_table.slt'

verify_schema = ['int','int','long','string','date']

verify_sql = 'SELECT * FROM demo_db.range_partition_upsert_table ORDER BY id, v1 ASC'

verify_data = """
1,1,50,1-50,2022-03-11
1,2,2,2-2,2022-03-12
1,3,2,3-2,2022-03-13
1,5,2,5-2,2022-03-15
1,8,2,8-2,2022-03-18
1,13,2,13-2,2022-03-13
1,21,2,21-2,2022-03-21
"""

drop_sqls = [
 'DROP TABLE IF EXISTS demo_db.range_partition_upsert_table',
 'DROP SCHEMA IF EXISTS demo_db'
]
